const courseData = [
  {
    id: 1,
    courseName: "طراحی سایت",
    courseMaster: "استاد محسن اسفندیاری",
    price: 5000000,
    view: 10,
    addTime: 14020210,
    like: 11,
  },
  {
    id: 2,
    courseName: "پایتون",
    courseMaster: "استاد مهدی اصغری",
    price: 430000,
    view: 14,
    addTime: 14020406,
    like: 12,
  },
  {
    id: 3,
    courseName: "دوره اصلی",
    courseMaster: "استاد حامد نظری",
    price: 650000,
    view: 13,
    addTime: 14021003,
    like: 21,
  },
  {
    id: 4,
    courseName: "ری اکت",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 1250000,
    view: 43,
    addTime: 14021111,
    like: 32,
  },
  {
    id: 5,
    courseName: "پایتون",
    courseMaster: "استاد محسن اسفندیاری",
    price: 2200000,
    view: 657,
    addTime: 14021221,
    like: 421,
  },
  {
    id: 6,
    courseName: "دوره اصلی",
    courseMaster: "استاد مهدی اصغری",
    price: 4200000,
    view: 32,
    addTime: 14020110,
    like: 312,
  },
  {
    id: 7,
    courseName: "ری اکت",
    courseMaster: "استاد حامد نظری",
    price: 690000,
    view: 543,
    addTime: 14020423,
    like: 213,
  },
  {
    id: 8,
    courseName: "دوره اصلی",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 1000000,
    view: 321,
    addTime: 14021221,
    like: 321,
  },
  {
    id: 9,
    courseName: "دوره اصلی",
    courseMaster: "استاد حامد نظری",
    price: 550000,
    view: 213,
    addTime: 14020805,
    like: 32,
  },
  {
    id: 10,
    courseName: "پایتون",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 5000000,
    view: 32,
    addTime: 14020921,
    like: 131,
  },
  {
    id: 11,
    courseName: "دوره اصلی",
    courseMaster: "استاد حامد نظری",
    price: 2350000,
    view: 12,
    addTime: 14020112,
    like: 42,
  },
  {
    id: 12,
    courseName: "دوره اصلی",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 4000000,
    view: 54,
    addTime: 14020708,
    like: 231,
  },
  {
    id: 13,
    courseName: "دوره اصلی",
    courseMaster: "استاد حامد نظری",
    price: 4250000,
    view: 653,
    addTime: 14020915,
    like: 321,
  },
  {
    id: 14,
    courseName: "پایتون",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 1000000,
    view: 4324,
    addTime: 14020221,
    like: 32,
  },
  {
    id: 15,
    courseName: "دوره اصلی",
    courseMaster: "استاد حامد نظری",
    price: 800000,
    view: 543,
    addTime: 14020723,
    like: 345,
  },
  {
    id: 16,
    courseName: "پایتون",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 1200000,
    view: 2343,
    addTime: 14020930,
    like: 6453,
  },
  {
    id: 17,
    courseName: "طراحی سایت",
    courseMaster: "استاد محسن اسفندیاری",
    price: 3420000,
    view: 432,
    addTime: 14020529,
    like: 54,
  },
  {
    id: 18,
    courseName: "دوره اصلی",
    courseMaster: "استاد حامد نظری",
    price: 870000,
    view: 4323,
    addTime: 14021127,
    like: 43,
  },
  {
    id: 19,
    courseName: "پایتون",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 250000,
    view: 532,
    addTime: 14020123,
    like: 321,
  },
  {
    id: 20,
    courseName: "دوره اصلی",
    courseMaster: "استاد حامد نظری",
    price: 2300000,
    view: 34,
    addTime: 14021212,
    like: 12,
  },
  {
    id: 21,
    courseName: "دوره اصلی",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 250000,
    view: 43,
    addTime: 14021111,
    like: 33,
  },
  {
    id: 22,
    courseName: "پایتون",
    courseMaster: "استاد مهدی اصغری",
    price: 430000,
    view: 4234,
    addTime: 14020313,
    like: 213,
  },
  {
    id: 23,
    courseName: "ری اکت",
    courseMaster: "استاد حامد نظری",
    price: 4200000,
    view: 34,
    addTime: 14020321,
    like: 2132,
  },
  {
    id: 24,
    courseName: "دوره اصلی",
    courseMaster: "استاد محمد بحرالعلوم",
    price: 2350000,
    view: 432,
    addTime: 14020221,
    like: 21,
  },
];
const newsData = [
  { id: 1, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 2, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 3, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 4, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 5, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 6, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 7, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 8, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 9, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 10, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 11, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 12, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 13, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 14, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 15, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 16, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 17, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 18, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 19, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 20, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 21, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 22, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 23, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 24, topic: "هوا", author: "فرامرز", number: 12 },
];
const masterData = [
  { id: 1, master: "استاد محمد بحرالعلوم", topic: "مدیدریت پژوهشگاه" },
  { id: 2, master: "استاد حامد نظری", topic: "مدرس دوره ی دیزاین" },
  { id: 3, master: "استاد مهدی اصغری", topic: "مدرس دوره ی ری اکت" },
  { id: 4, master: "استاد محسن اسفندیاری", topic: "مدرس دوره ی ری اکت" },
];
const courseNameData = [
  { id: 1, courseName: "پایتون" },
  { id: 2, courseName: "ری اکت" },
  { id: 3, courseName: "طراحی سایت" },
  { id: 4, courseName: "دوره اصلی" },
];
const relatedData = [
  { id: 1, courseName: " هااا ", courseMaster: "میو  نیگا", price: 100000 },
  { id: 2, courseName: " میو ", courseMaster: "میو  نیگا", price: 100000 },
  { id: 3, courseName: " میو ", courseMaster: "میو  نیگا", price: 100000 },
];
const relatedNews = [
  { id: 1, topic: "هوا", author: "فرامرز", number: 12 },
  { id: 2, topic: "هاوا", author: "فرامرز", number: 12 },
  { id: 3, topic: "هوا", author: "سمرز", number: 12 },
];
const courseCommentData = [
  {
    text: "خووووووووووبببب بوووووووووووود",
    userName: "امین",
    userLogo: "https://picsum.photos/200/300",
    Response: {},
    date: "۳۰ مرداد",
  },
  {
    text: "خوب بود",
    userName: "محمد جواد",
    userLogo: "https://picsum.photos/200/500",
    Response: {
      text: "خوب بود",
      userName: "امی",
      userLogo: "https://picsum.photos/200/700",
      Response: {},
      date: "۳۰ بهمن",
    },
    date: "۱۰ فروردین",
  },
  {
    text: "بد بود",
    userName: "اشکان محمدی اصل",
    userLogo: "https://picsum.photos/200/400",
    Response: {},
    date: " دیروز ",
  },
];
const ArticleCommentData = [
  {
    text: "نه حال نکردم",
    userName: "امین",
    userLogo: "https://picsum.photos/200/300",
    Response: {},
    date: "۳۰ مرداد",
  },
  {
    text: "خوب بود",
    userName: "محمد جواد",
    userLogo: "https://picsum.photos/200/500",
    Response: {
      text: "خوب بود",
      userName: "امی",
      userLogo: "https://picsum.photos/200/700",
      Response: {},
      date: "۳۰ بهمن",
    },
    date: "۱۰ فروردین",
  },
  {
    text: "بد بود",
    userName: "اشکان محمدی اصل",
    userLogo: "https://picsum.photos/200/400",
    Response: {},
    date: " دیروز ",
  },
];
const myCourseData = [
  {
    coursePic: "https://picsum.photos/200/200",
    courseName: " میو ",
    courseMaster: "میو میو نیگا",
    term: "زمستان",
    date: "۱۴۰۲/۰۴/۲۹",
    price: 190000,
  },
  {
    coursePic: "https://picsum.photos/200/300",
    courseName: " میو میو",
    courseMaster: "میو میو نیگا",
    term: "تابستان",
    date: "۱۴۰۳/۰۸/۲۰",
    price: 300000,
  },
  {
    coursePic: "https://picsum.photos/200/400",
    courseName: " میو میو",
    courseMaster: "میو میو نیگا",
    term: "بهار",
    date: "۱۴۰۱/۱۲/۱۰",
    price: 400000,
  },
];
const allCourseData = [
  {
    coursePic: "https://picsum.photos/200/200",
    courseName: " میو ",
    courseMaster: "میو میو نیگا",
    term: "زمستان",
    date: "۱۴۰۲/۰۴/۲۹",
    price: 190000,
  },
  {
    coursePic: "https://picsum.photos/200/300",
    courseName: " میو میو",
    courseMaster: "میو میو نیگا",
    term: "تابستان",
    date: "۱۴۰۳/۰۸/۲۰",
    price: 300000,
  },
  {
    coursePic: "https://picsum.photos/200/400",
    courseName: " میو میو",
    courseMaster: "میو میو ",
    term: "بهار",
    date: "۱۴۰۱/۱۲/۱۰",
    price: 980000,
  },
  {
    coursePic: "https://picsum.photos/200/500",
    courseName: " ها میو",
    courseMaster: "میو میو نیگا",
    term: "بهار",
    date: "۱۴۰۱/۰۷/۱۹",
    price: 1000000,
  },
  {
    coursePic: "https://picsum.photos/200/600",
    courseName: " ها ها ",
    courseMaster: "میو  نیگا",
    term: "هاا",
    date: "۱۴۰۱/۰۲/۰۳",
    price: 480000,
  },
];

export {
  courseData,
  newsData,
  masterData,
  relatedData,
  courseCommentData,
  ArticleCommentData,
  myCourseData,
  allCourseData,
  relatedNews,
  courseNameData,
};
